### ISSUE TITLE
WithExtraAttributes doesn't really work

### ISSUE THREAD

**Issue by niladam** [spatie/laravel-schemaless-attributes#13]
First of all, thank you for this package. I was really looking for something simple that can help me on a project i'm working on. 

I realise this package is 0.0.3 and that it's a new one but i just found a bug :)

I'm attempting this:

```php
$models = Model::withExtraAttributes(['name' => 'value', 'name2' => 'value2'])->get();
```

I'm getting this:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."name"' = ? and `extra`->'$."name2"' = ? and
```

I'm using this on **Valet** (on mac), using **PHP 7.25**, with **MariaDB 10.2.14** (via brew);

Maybe you can guide me or point me in the right direction ? (edit: replaced typo)

**Comment by niladam** [comment]
I think the problem is in [SchemalessAttributes.php (112-114)](https://github.com/spatie/laravel-schemaless-attributes/blob/master/src/SchemalessAttributes.php#L112-L114)

**Comment by freekmurze** [comment]
This package requires a db that has support for json columns: https://github.com/spatie/laravel-schemaless-attributes#requirements

**Comment by niladam** [comment]
Thank you. I didn't actually read that.

**Comment by dododedodonl** [comment]
MariaDB now supports JSON fields, but the select syntax is different. The mysql driver in laravel has to be patched. Something like https://github.com/ybr-nx/laravel-mariadb can be used.
