### ISSUE TITLE
Does it support PostgreSQL ?

### ISSUE THREAD

**Issue by kamrava** [spatie/laravel-schemaless-attributes#15]
Hi,
Does it support PostgreSQL **json** and **jsonb** columns?

**Comment by niladam** [comment]
According to the docs:

`This package requires a database with support for json columns like MySQL 5.7 or higher.`

I think it does.

**Comment by MattWohler** [comment]
@kamrava , yes.

This package is essentially nice wrapper around the built-in JSON support for Laravel's Query Builder !

**Comment by freekmurze** [comment]
It should support PostgreSQL 😎
