### ISSUE TITLE
Allow passing of default value if not found for get

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-schemaless-attributes#17]
Example:

$model->extra_attributes->get('table.color', 'Green');

like how data_get and array_get does it in Laravel helpers

It would be great to have this. Thanks!

**Comment by freekmurze** [comment]
I'd accept a PR with tests and an updated readme that adds this to the package.

**Comment by jarektkaczyk** [comment]
Don't use `get` as it is already a method on the builder and you could get in trouble. Make it explicit instead.

**Comment by ziming** [comment]
Just adding a note that it is fixed by https://github.com/spatie/laravel-schemaless-attributes/pull/18 for those searching about it
