### ISSUE TITLE
Discourage use of $casts to array or write a warning about its quirks?

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-schemaless-attributes#19]
In the use of this package. I discovered the following after doing some exhaustive tests:

Let's say I have all my models with extra_attributes have the following casts

```php
protected $casts = [
    'extra_attributes' => 'array
]
```

Now let me do a `User::create(...)` with a json string

```php
// Example:

User::create([
    // ... other fields
   'extra_attributes' => '{"race" : "Japanese" }'
]);
```

In the database, 'extra_attributes" will be stored like this:

```json
"{\"race\" :  \"Japanese\"}"
```

That above will, as we expect cause, an issue when doing `$record->extra_attributes->all()` as it is a string that can't be casted to an array

Initially, I thought just making sure I always pass an array or object to extra_attributes will work fine

```php
User::create([
    // Other fields...

    // json_decode('{"race" : "Japanese" }', true) works too.
   'extra_attributes' => json_decode('{"race" : "Japanese" }'), 
]);
```

Sure enough the json is stored correctly in the database without all those `\` characters.

But the examples below give either 1 of the 2 errors as they expect a string instead

- `ErrorException : Object of class stdClass could not be converted to string`
- `ErrorException : Array to string conversion`

Both `json_decode(..., true)` and `json_decode(...)` are tried

```php
// See https://github.com/laravel/framework/issues/19144
// It need to be a String here!
User::where('id', 5)->update('extra_attributes', json_decode('{"race" : "Japanese" }'));

$user->bag()->update([
    // It need to be a String!
    'extra_attributes' =>  json_decode('{"colour" : "blue" }')
]);
```

However in the following case, it is the reverse, Laravel expects an array to be passed in or you can expect errors later:

```php
$bag->update([
     // need to be an array or object here!
    'extra_attributes' =>  json_decode('{"colour" : "blue" }')
 ]);

$user->bag()->create([
    // other fields

    // needs to be an array or object here! This is different from $user->bag()->update(...) !
    'extra_attributes' =>  json_decode('{"colour" : "blue" }', true)
]);
```

I did not test on `BelongsToMany`, `ManyToMany` relationships.

As you can see. It can be quite confusing on when Laravel use Eloquent update() with $casts and when it use QueryBuilder update().etc

Another quirk to be aware of is doing `$user->extra_attributes` give you a SchemalessAttributes object rather than an array even if you cast it. It may be good to highlight that in the README.md so people who are adding this to an existing project will be more aware of it & do `$user->extra_attributes->all()`

Hence I like to suggest the following addition or changes to README.md (1 of them or mix):

- Keep the casts to array & but say how important it is to always update `extra_attributes` seperately with the package methods, even when creating the extra_attributes json for the 1st time

- Strongly discourage cast to array on the field & tell people to always do a json_encode or pass a json string when using `Eloquent` or `QueryBuilder` `create()` and `update()` method for extra_attributes for consistency reasons. After all `$user->extra_attributes` gives us back a `SchemalessAttributes` object not an array after all. So the casting felt redundant in some way

- (Least Favoured). Do a more exhaustive test than what I did & list out all the "quirks" to be aware of. But this may be good too as part of learning

Thanks!

**Comment by ziming** [comment]
@freekmurze But I'm not sure which of the 3 approach you prefer?

**Comment by freekmurze** [comment]
I'd go for option number 1.

**Comment by ziming** [comment]
Alright I will try to get it done during the weekends
