### ISSUE TITLE
Serializing To JSON does not work

### ISSUE THREAD

**Issue by lewebdalex** [spatie/laravel-schemaless-attributes#21]
Hi,

Thanks for the great package.

I've implemented this package for a Model used on my API.

**Working**
Basic implementation such as `Post::findOrFail($id)`works great.

**Not Working**
But when casted to a json with `Block::findOrFail($id)->toJson()`it does return an empty Array and instead of its values.

Thank you,
Regards,

**Comment by freekmurze** [comment]
We recently added Laravel`s `Arrayable interface to `SchemalessAttributes`.

Does that fix this issue?

**Comment by lewebdalex** [comment]
It does with last night release. Thanks!
