### ISSUE TITLE
Undefined property: $extra_attributes

### ISSUE THREAD

**Issue by cfreak** [spatie/laravel-schemaless-attributes#25]
I have added 

```php
 public function __get($key)
    {
        if ($this->extra_attributes->has($key)) {
            return $this->extra_attributes->get($key);
        }

        return parent::__get($key);
    } 
```

But when accessing with:

```php
$model->test
```

i get an Error: Undefined property: $extra_attributes

**Comment by cfreak** [comment]
What i'm doing wrong?

**Comment by freekmurze** [comment]
The  `extra_attributes` property doesn't really exist on your model. This is handled by Laravel's magic.

**Comment by cfreak** [comment]
But it is described in your Reader like this, or do i unterstand it wrong?

**Comment by freekmurze** [comment]
You're right, I'll take a look after the weekend.

**Comment by freekmurze** [comment]
It does not work indeed, I removed the section from the readme.
