### ISSUE TITLE
Fetch models with nested attributes using scope

### ISSUE THREAD

**Issue by JoeDawson** [spatie/laravel-schemaless-attributes#27]
Hello,

I'm currently trying to fetch users in my application that have an attribute "on". Here's an example of a user model.

```json
{
  "id": 1,
  "name": "JoeDawson",
  "attributes": {
    "emails": {
      "weekly": "on",
      "promotional": "on"
    }
  }
}
```
I'm trying to fetch users with their `weekly` email attribute "on".

```php
$users = User::withAttributes(['emails' => ['weekly' => 'on']])->get();
```

However this returns an empty collection. Am I doing something wrong?

**Comment by freekmurze** [comment]
Not sure, but it probably has something to do with the fact that you're trying to match a partial nested array.


Does this work?

```php
$users = User::withAttributes(['emails' => ['weekly' => 'on', 'promotional' => 'on']])->get();
```

The scope simply defers to the json query methods from Laravel: https://github.com/spatie/laravel-schemaless-attributes/blob/e853155e58eac905939f523542b5bf3472abe7a6/src/SchemalessAttributes.php#L124

**Comment by JoeDawson** [comment]
Hi @freekmurze,

Unfortunately this is also returning an empty collection.

To be sure my scope was working, I created a "test" attribute;

```json
{
  "id": 1,
  "name": "JoeDawson",
  "attributes": {
    "test": "on",
    "emails": {
      "weekly": "on",
      "promotional": "on"
    }
  }
}
```

And this is working as expected;

```php
$users = User::withAttributes(['test' => 'on'])->get();
```

**Comment by JoeDawson** [comment]
Nevermind, this works!

```php
$users = User::withAttributes(['emails->weekly' => 'on'])->get();
```
