### ISSUE TITLE
Can I use this on existing json columns?

### ISSUE THREAD

**Issue by num3thod** [spatie/laravel-schemaless-attributes#29]
First off, thanks for yet another handy package.

I'm trying to use this package on an existing JSON column, rather than creating a migration with `$table->schemalessAttributes('extra_attributes');` but am getting an error.

`Indirect modification of overloaded property App\Models\Auth\User::$settings has no effect`

Thanks in advance.

**Comment by freekmurze** [comment]
This is error is not caused by this package.

Probably you are doing something like

```php
$user->settings[] = 'new setting':
```

Due to some magic going on behind the scenes that won't work.

Try refactoring to this:

```php
$settings = $user->setttings;
$settings[] = 'new setting`;
$this->settings = $settings;
```
