### ISSUE TITLE
How can I foreach $yourModel->extra_attributes

### ISSUE THREAD

**Issue by OranTing** [spatie/laravel-schemaless-attributes#30]
```
foreach ($res->extra_attributes as $key => $extra_attribute) {
        dump($extra_attribute);
}
```
This will return NULL.
How can I foreach $res->extra_attributes ?

Thank you

**Comment by freekmurze** [comment]
Try looping `$res->extra_attributes->all()`.

**Comment by freekmurze** [comment]
Added a test to make sure it's working. https://github.com/spatie/laravel-schemaless-attributes/commit/dc71c567cc95a9072f1da83eb726411e3a625c8f

**Comment by OranTing** [comment]
Thank you
