### ISSUE TITLE
Question: Serializing JSON attributes for export

### ISSUE THREAD

**Issue by alariva** [spatie/laravel-schemaless-attributes#32]
Hi!

I've been using `laravel-schemaless-attributes` some time ago and it's doing great! Thanks for this package.

This time I'd like to address an issue (more of a request for suggestions than a problem) that I'm experiencing when trying to serialize for export.

I started using https://github.com/mathieutu/laravel-json-syncer little time ago for exporting models into JSON, and so far I got great results with standard models (A.K.A. without schemaless attributes).

But I'm facing an exception `Return value of Spatie\SchemalessAttributes\SchemalessAttributes::getRawSchemalessAttributes() must be of the type array, string returned` when trying to export. This of course makes sense, because the schemaless attribute needs to be returned as `array`.

So my question to the point is: What would you suggest as a straightforward solution to be able to serialize for export the schemaless attribute?

I see 3 possible paths:
  * `laravel-json-syncer` (The exporter package) should serialize the array attribute. [Reference](https://github.com/mathieutu/laravel-json-syncer/issues/2)
  * `laravel-spatie-schemaless-attributes` should provide a method to request the serialized version of attribute, so it can be consumed by any client for exporting capabilities.
  * The application should take care of the data conversion. I see this feasible, however it feels a bit cumbersome and I'd actually would not know how to handle this in an elegant way.

Of course, I understand that it's possible that `laravel-schemaless-attributes` should not be "export-aware". That's why I'm just evaluating paths and asking for advice from your experience and knowledge on the package's features.

Thanks in advance and best regards,

**Comment by freekmurze** [comment]
> Of course, I understand that it's possible that laravel-schemaless-attributes should not be "export-aware".

Indeed, our package should not be export aware and we will not be making any modifications. I recommend that you open an issue at Mathieu's package to learn how he would handle it in his package.

**Comment by mathieutu** [comment]
Hi @freekmurze, it seems to come from one of your internal method, which is not returning the expected type of data. I don't know how we can handle that on our side, because the exporter is at a far higher level of all of that, as it only uses a `$model->$attribute` way to retrieve attributes. We don't handle at all any custom way, we just get the attribute. No more, no less.


The conversion to json, is made a while after this operation, just by a classic `toJson` collection method, so it has no link with that.

@alariva I think we need more information about your error. Could you dump the result of this method (before the error)? Maybe it's just that you're attribute is wrong, and Spatie package can't decode it? I don't know where comes from the problem, but imo it can't come from my package. 

See the code of the function here : 
https://github.com/mathieutu/laravel-json-syncer/blob/3ae2baf757b28ef19d92800edf7466c06e7de687/src/Helpers/JsonExporter.php#L35

**Comment by alariva** [comment]
Thanks @freekmurze and @mathieutu for putting a bit of your time for an eye on this issue.

Let me put this clear; **this is not by any means an error or failure affecting production** .

In fact, both packages work just perfect when installed separately.

The point with this issue/question is that an actual challenge araises when the packages work **combined** in the same application.

    Return value of Spatie\SchemalessAttributes\SchemalessAttributes::getRawSchemalessAttributes() must be of the type array, string returned

*Why does this happen?*

`laravel-json-syncer` grabs all the attributes of a model, and serializes them for JSON export. As long as they are all scalars, there will be no problem there (i.e. with plain/default models). And that's OK.

`laravel-schemaless-attributes` allows the application to use native SQL JSON datatype for storing nested json attributes on a single model attribute. This comes in handy when dealing with model preferences, configuration and other extra data that does not require a very strict storage structure. The "tradeoff" for using this, is that now some attribute outputs will behave as array instead of scalar. And of course, that's the very reason for what the package is intended for, so that's also OK.

So I guess the situation is clear at this point; when `laravel-json-syncer` reads this special attribute and expects a scalar value, it finds out that it's actually an array willing to be casted as string straight away.

It is clear that none of the packages should be aware of each other. And I think it's also fair to think that we want packages to be the least instrusive possible as to remove space for inter-operational conflicts. I understand that is not always possible.

But since both packages actually handle different domains, I think, why should there ever exist any technical conflict?

I'm also aware that it's me as the app owner who may take the final decisions on how the **composer-require cocktail** will look like. To be honest, I see everything will work just fine.

So, since the solution is already spotted, meaning that serializing the array attribute for export, and de-serializing for import would be a way to go about it, I'm wondering **how to achieve this the most elegant way and least impactful for packages**.

Doing so from the app is feasible, but I'm just asking for help as it feels clumsy to contaminate the application code with kind of forced patches. Maybe there's a way to build a generic adapter or so. But I wanted to know how much of this logic could be encapsulated as a package, since it's absolutely possible that **anyone** installing both packages combined will most likely run into the same situation.

That's it and thanks again for your patience!

**Comment by freekmurze** [comment]
Thank you for your detailled explanation.

> It is clear that none of the packages should be aware of each other.
I agree with this. 

Because I don't use the json syncer package and am not experiencing any problems, I'm not going to invest time in interoperability. If this can be fixed in a, non breaking, non unobtrusive way, I'd be open for a PR.

**Comment by mathieutu** [comment]
>As long as they are all scalars, there will be no problem there.

As I said before, `laravel-json-syncer` doesn't care about the type of your field. It just get the field, put it in a collection and call a `toJson` method. The error comes from internal php type checking *inside* the `getRawSchemalessAttributes()` far before the serialization.

@alariva could you provide a repo for reproduction? I'll check it and see if something could be done.

**Comment by alariva** [comment]
Sure, I can do that. I will:

  * Create a sandbox repo with a behavior reproduction MVP
      * Install `laravel-schemaless-attributes`
      * Add a JSON attribute for a base model
      * Install `laravel-json-syncer`
      * Add a basic json export call (reproduces the issue)

I will also provide an app level workaround which we could analyze for encapsulation if it happen to be packable logic.

Also let's use that repo (will post reference) as a middleground for discussion and come back to `laravel-schemaless-attributes` in case we get to a very accurate finding/need regarding the package.

Thanks!

**Comment by alariva** [comment]
Just for clear reference. For anyone facing a similar problem, [I've done the tests to verify that there is no conflict at all with both packages installed simultaneously](https://github.com/alariva/laravel-json-syncer-schemaless-attributes). It was my bad and I've already spotted the problem was somewhere else.
