### ISSUE TITLE
Question: Any suggestion for more elegant save solution?

### ISSUE THREAD

**Issue by EricBusch** [spatie/laravel-schemaless-attributes#36]
Hi

Thanks for this awesome package! It's perfect for so many of my projects.

I'm wondering if there's a more elegant solution for saving attributes in my controller?

Right not my store/update methods look like this:

```
$model->extra_attributes->set('address.street_1', request('address_street_1', null));
$model->extra_attributes->set('address.city', request('address_city', null));
$model->extra_attributes->set('address.province', request('address_province', null));
$model->extra_attributes->set('address.postal_code', request('address_postal_code', null));
$model->save();
```

Do you have any suggestions to reduce the number of `set()` calls in the controller or is this how you would do it?

Thanks again,
Eric

**Comment by sebastiandedeyne** [comment]
Maybe we should allow associative array in `set`, what do you think @freekmurze?

**Comment by sebastiandedeyne** [comment]
Maybe we should allow associative array in `set`, what do you think @freekmurze?

**Comment by freekmurze** [comment]
Seems good to allow an associative array. I'd accept a non-breaking, fully tested PR that adds this to the package. Be sure to also add an example to the readme.

**Comment by mtimbs** [comment]
PR submitted https://github.com/spatie/laravel-schemaless-attributes/pull/37

**Comment by freekmurze** [comment]
We'll handle this further in #37

**Comment by EricBusch** [comment]
Thanks @mtimbs and Spatie!
