### ISSUE TITLE
Use withExtraAttributes equals null or false

### ISSUE THREAD

**Issue by lucasdcrk** [spatie/laravel-schemaless-attributes#40]
How can I use withExtraAttributes with a value that can be null OR false
eg: If I want to query all the users that have a null or false disableNewsletter attribute

`User::withProperty('disableNewsletter', false)->get();` Return all the users that have disableNewsletter explicitely set to false

`User::withProperty('disableNewsletter', null)->get();` Return all the users that haven't any disableNewsletter attribute

I am looking for a way to query `User::withProperty('disableNewsletter', false || null)->get();` (to illustrate)
Is the only way to achieve this is to combine both collections?

**Comment by niladam** [comment]
I haven't tried this but maybe this works?:

`User::withProperty(['disableNewsletter' => false, 'disableNewsletter' => ''])->get();`

Also, make sure to double check this as my reply was added from my mobile phone.

**Comment by niladam** [comment]
Just a sidenote, you should probably cast `disableNewsletter` for easier maintenance and usage in the future.

**Comment by lucasdcrk** [comment]
Issue resolved
For anyone seeing this issue later, I used the via($notifiable) method to limit the users that will receive the notification.

`public function via($notifiable)
    {
        if ($notifiable->property->disableNewsletter) {
            return [];
        }

        return ['mail'];
    }`
