### ISSUE TITLE
Json vs Jsonb

### ISSUE THREAD

**Issue by securit** [spatie/laravel-schemaless-attributes#62]
Can I ask why you chose to use JSON as the default Postgres format rather than JSONB? when the postgres documentation states

https://www.postgresql.org/docs/current/datatype-json.html

"In general, most applications should prefer to store JSON data as jsonb, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys."

The json and jsonb data types accept almost identical sets of values as input. The major practical difference is one of efficiency. The json data type stores an exact copy of the input text, which processing functions must reparse on each execution; while jsonb data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed. jsonb also supports indexing, which can be a significant advantage.

Because the json type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as well as the order of keys within JSON objects. Also, if a JSON object within the value contains the same key more than once, all the key/value pairs are kept. (The processing functions consider the last value as the operative one.) By contrast, jsonb does not preserve white space, does not preserve the order of object keys, and does not keep duplicate object keys. If duplicate keys are specified in the input, only the last value is kept.

**Comment by freekmurze** [comment]
We don’t use Postgres for our projects, feel free to modify the default migration to your liking.

**Comment by nathan-io** [comment]
@securit this worked for me:

In `SchemalessAttributesServiceProvider.php`:

```
<?php

namespace Spatie\SchemalessAttributes;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\ServiceProvider;

class SchemalessAttributesServiceProvider extends ServiceProvider
{
    public function register()
    {
        Blueprint::macro('schemalessAttributes', function (string $columnName = 'schemaless_attributes') {
			if(config('database.default') == 'pgsql') {
				return $this->jsonb($columnName)->nullable();
			} else {
				return $this->json($columnName)->nullable();
			}
        });
    }
}
```

**Comment by nathan-io** [comment]
@freekmurze 

The above could be a nice addition, I'm curious if you'd consider merging a PR like this.

I'm just not sure about the `if(config('database.default')` condition. Seems it would be better to check the driver of the current connection, in case it's different than `default`. I'm not sure how to determine the current connection/driver in the service provider context, but could look into it.
