### ISSUE TITLE
Practices for version control and documentation of schemaless attribute properties?

### ISSUE THREAD

**Issue by nathan-io** [spatie/laravel-schemaless-attributes#63]
Thanks so much for this package! 

This is not an issue, but a question. We'd like to use this package on some of our `User` model attributes.

My question is about version control for schemaless properties - or in other words, maintaining consistency in existing records when we add or remove JSON properties, or make new or existing properties required.

For example, let's say that our migration includes just the example `extra_attributes` column in the `users` table.

For our first few thousand `Users`, we store certain properties there.

We later find that `extra_attributes` needs some additional properties, and some of those properties will be expected/required by our application. 

So we update the `User` create method to set values for those new properties as desired. But we still need to set them for existing `users` records, or else the application will fail when handling requests from those users because expected values are empty.

But what is the best way to find previously created `Users` who don't have those new properties and add them?

That example is simple of course, I'm just considering for more complex situations such as when:

- we create, drop, or rename multiple properties
- a newly created property is now required to be set in order for something to work

Since none of the changes to `extra_attributes` properties would be committed through migrations,  it seems we'd need to create an artisan command which makes the updates to existing `users` records, and include it in the same commit where we introduce the new `extra_attributes` properties. Then we could include that artisan command in our deploy script when deploying the update.

Or, we could add empty checks in the model whenever accessing those newly required properties (or remove empty checks for dropped properties).

While these approaches would work, I was just hoping there could be a more elegant solution.

The other question is documentation. Typically, even if we were not using `$fillable` in a model, a developer can look at the migrations and/or current table structure and easily see the available attributes/columns. 

But with schemaless attributes, we don't have a central place in the codebase where the possible keys/properties are defined.

Just wanted to see how some have approached these questions. Thank you!

**Comment by nathan-io** [comment]
A custom validation rule applied to the model (as described [here](https://stackoverflow.com/questions/51107161/laravel-defining-rules-or-schema-for-a-json-field-column)) seems like it could be part of the solution for enforcing integrity and tracking changes over time.

The custom validation rule would serve as a place where we could clearly define and track any required and/or deprecated columns, and if `!passes()` then we could update that particular record (remove the deprecated property, or add the required property with some default value, etc.).

That's still a little messy because it only updates records on an as-needed basis.

If we wanted to validate and/or update all records at once, the alternative would be to create some artisan command which made `whereJsonContains` queries to update and standardize that column in all existing records.

**Comment by wsamoht** [comment]
Is there a reason why you don't create a DB migration? That is how I add new properties to an existing schemaless/json field when I add new properties in my code so my code doesn't blow up :)

Here is an example from my codebase.

```php
class AddIncludeSponsorToLocations extends Migration
{
    public function up()
    {
        DB::table('locations')
            ->whereNotNull('forecast_options')
            ->update([
                'forecast_options' => DB::raw(
                    "json_insert(forecast_options, '$.include_sponsor', true)"
                )
            ]);
    }

    public function down()
    {
        DB::table('locations')
            ->whereNotNull('forecast_options')
            ->update([
                'forecast_options' => DB::raw(
                    "json_remove(forecast_options, '$.include_sponsor')"
                )
            ]);
    }
}
```

**Comment by nathan-io** [comment]
Thanks for your message! 

Migrations are a good canonical record of what properties should exist on the schemaless attribute, and what their defaults should be, but it's hard to quickly identify all changes to a particular model attribute and its properties that way. 

Another question I'd have is that in your example, `forecast_options` is the column/model attribute, and `include_sponsor` is the new property. I'm not sure about the behavior of `whereNotNull('forecast_options')` there, because `forecast_options` could have another property. So (and I could be completely wrong about this) is it possible that migration could cause an existing model's `forecast_options.include_sponsor` to be reset to `true` when it was previously false? 

The use case you cited is pretty straightforward (we have a single key called `include_sponsor` with a default of `true`), but what about when it's more complicated? For example, there is no default value, or we need some logic or even an external request to derive the value (for example, we get a user's timezone and locale data from Google API). So in these cases you could just set the default to `null`, but then what's the point of even doing the migration?

So a big part of my initial question/concern was:

> But with schemaless attributes, we don't have a central place in the codebase where the possible keys/properties are defined.


So with the 1.18.0 release which adds support for multiple schemaless attributes on a model, I've been doing this in the model:

```
    public $schemalessAttributes = [
		'name', // prefix, first, middle, last, suffix, full
		'phone', // type, label, canReceiveSms, countryIsoCode, countryDialCode, areaCode, number, extension
               ...
```

So anyone looking at the model can immediately see the available properties on that attribute, and we can see how that changes over time in one file on one line.

So for me, that's a workable form of shorthand documentation on these attributes.

---

As for the validation piece, I've come to think that I may have answered my own question in the original post:

> Or, we could add empty checks in the model whenever accessing those newly required properties (or remove empty checks for dropped properties).

Ultimately I think this is unavoidable because migrations alone couldn't be viewed as foolproof IMO. 

No doubt there are many ways to efficiently handle validation on schemaless attributes, such as writing a custom validator for that attribute, or accessing properties via custom getters rather than directly, so you can put whatever validation logic will keep things from crashing right there in the model.

**Comment by wsamoht** [comment]
Very good points. I do `whereNotNull('forecast_options')` because the field can be null (no JSON document for the DB row) because it was never initiated. I can't update the JSON document if it doesn't exist. When it gets created, the new property will be there because my logic would now include it.

So far, I have always had a default value and haven't needed to use another service or set of logic to generate the value.

For nested properties, I do the following:
```php
// Adding temperature_units and measurement_system to location
DB::table('locations')
    ->whereNotNull('forecast_options')
    ->update([
        'forecast_options' => DB::raw(
            "json_insert(forecast_options, '$.location.temperature_units', 'fahrenheit', '$.location.measurement_system', 'imperial')"
        )
    ]);
```

My partial schema is as follows:
- location
  - temperature_units
  - measurement_system
- include_sponsor
- forecast_periods[]
  - name
  - sponsor
- etc.

I get your point of not easily being able to know what properties exist in the JSON document. Right now I store it in a Google Doc which isn't optimal. I wonder if the best option would be to build out PHP objects to represent the JSON document and then they get converted when they get saved in the model. I would have to think about that some more. There has to be a best practice for those using a NoSQL DB :)
