### ISSUE TITLE
isset() and empty() return incorrect result

### ISSUE THREAD

**Issue by nathan-io** [spatie/laravel-schemaless-attributes#69]
Hi, thanks for this wonderful package!

This issue is on v1.8.0, Laravel 7.26.1.

In our `User` model, we have some schemaless attributes including `name`.

Example of a Tinker session demonstrating the issue:

```
>>> $user
=> App\User {#4458
     id: 1,
     name: "{"first":"John","last":"Doe","formatted":"John Doe"}",
     email: "mail@mail.com",
     phone: null,
     locale: "en",
     timezone: null,
     address: null,
     birthday: null,
     avatar: null,
     gender: null,
     privacy: null,
     email_verified_at: null,
     phone_verified_at: null,
     banned_at: null,
     deleted_at: null,
     created_at: "2020-09-13 03:00:00",
     updated_at: "2020-09-13 03:01:35",
   }

>>> isset($user->name->first)
=> false
>>> empty($user->name->first)
=> true
>>> empty($user->name->get('first'));
=> false
```

---

As you can see, `get()` does return the correct result for `empty()`, but not when accessing the property directly.

I was also going to test this behavior on nested properties but am having trouble setting those in the first place. Creating a separate issue for that.

Thank you.

**Comment by freekmurze** [comment]
I'm thinking it is related to this: https://freek.dev/1057-when-empty-is-not-empty

I'd accept a PR with tests that fixes this.

**Comment by nathan-io** [comment]
This is working for me, added after `__set()` in `SchemalessAttributes.php`:

```
	public function __isset($name)
	{
		$property = $this->get($name);

		return isset($property);
	}
	
	public function __empty($name)
	{
		$property = $this->get($name);

		return empty($property);
	}
```

Will see about getting a PR with tests for you.

**Comment by freekmurze** [comment]
Fixed in latest release
