### ISSUE TITLE
Set nested properties

### ISSUE THREAD

**Issue by invaders-xx** [spatie/laravel-schemaless-attributes#77]
I am using 1.8.3 version on Laravel 8 and it seems that $model->extra_attribute->set('value1.value2.value3.value4', value5) does not work ?
Is that correct ? Is there a simple way to make it working ?

Many thanks in advance,

David

**Comment by freekmurze** [comment]
Check the tests to see if it is supported. If it is not I'd appreciate a PR with tests that adds this to the package.

**Comment by faisuc** [comment]
@invaders-xx Base on the tests. This feature is already implemented in the package.

https://github.com/spatie/laravel-schemaless-attributes/blob/a44a3d1f7c275ab2ee5435c08e50cea913bb89d6/tests/HasSchemalessAttributesTest.php#L101-L108
