### ISSUE TITLE
Rewrite package with Eloquent value object casting

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-schemaless-attributes#78]
Now that Eloquent supports custom casts with [value object casting](https://laravel.com/docs/8.x/eloquent-mutators#value-object-casting), I believe we could vastly improve the API and flexibility of this package, and remove a bunch of code in the process.

This is the current readme example:

```php
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Spatie\SchemalessAttributes\SchemalessAttributes;

class TestModel extends Model
{
    // ...

    public $casts = [
        'extra_attributes' => 'array',
    ];

    public function getExtraAttributesAttribute(): SchemalessAttributes
    {
        return SchemalessAttributes::createForModel($this, 'extra_attributes');
    }

    public function scopeWithExtraAttributes(): Builder
    {
        return SchemalessAttributes::scopeWithSchemalessAttributes('extra_attributes');
    }

    // ...
}
```

With value object casting, it could look like this:

```php
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Spatie\SchemalessAttributes\SchemalessAttributes;

class TestModel extends Model
{
    // ...

    public $casts = [
        'extra_attributes' => SchemalessAttributes::class,
    ];

    // ...
}
```

This would be a substantial rewrite of the package. We probably won't be picking this up ourselves soon. If someone else wants to pick this up, please respond below!

This is a great issue for first-time contributors, if needed, I can provide additional guidance and do in-depth PR reviews in the process.

**Comment by tanseercena** [comment]
Hi, 

I am ready to help you with this.

@sebastiandedeyne it will be great if you provide some PR process etc.

Thanks

**Comment by al-mootasem** [comment]
Would love this to be my very first contribution to open source!
I have read the guidelines and curious to know how the process goes?

**Comment by patinthehat** [comment]
I'll take this on, as it will give me the opportunity to also do the PHP 8 only upgrade.

**Comment by sebastiandedeyne** [comment]
Thanks for the offers for help, looks like this was taken care of before I even got back 😅
